#!/usr/bin/env bash

# Color codes
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
RED='\033[1;31m'
NC='\033[0m' # No Color

# Print ASCII art
echo -e "${GREEN}"
echo "                                 d8b             " 
echo "                                Y8P              "
echo "                                                 "
echo "88888b.  .d88b.  .d88b. 888  88888888888b.d88b.  "
echo "888 \"88bd8P  Y8bd88\"\"88b888  888888888 \"888 \"88b "
echo "888  88888888888888  888Y88  88P888888  888  888 "
echo "888  888Y8b.    Y88..88P Y8bd8P 888888  888  888 "
echo "888  888 \"Y8888  \"Y88P\"   Y88P  888888  888  888 "        
echo -e "                                                 ${NC}"
echo -e "${BLUE}-- @joaoofreitas${NC}"

# Detect the package manager
if command -v apt-get &>/dev/null; then
    PM='apt-get'
elif command -v dnf &>/dev/null; then
    PM='dnf'
elif command -v yum &>/dev/null; then
    PM='yum'
elif command -v pacman &>/dev/null; then
    PM='pacman'
else
    echo -e "${RED}Unsupported package manager. Please install 'unzip', 'curl' and 'ripgrep' manually.${NC}"
    exit 1
fi


# Prompt user for default Alacritty setup
read -p "Do you want to use the default Alacritty setup? (y/n): " use_default

if [[ "$use_default" =~ ^[Yy]$ ]]; then
    # Use default setup
    echo "Using default Alacritty setup"
     
    # Create alacritty.yml content
    ALACRITTY_CONTENT=$(cat <<EOF
import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

font:
  normal:
    family: JetbrainsMonoNerdFont
    style: Regular
  bold:
    family: JetbrainsMonoNerdFont
    style: Bold
  italic:
    family: JetbrainsMonoNerdFont
    style: Italic
  bold_italic:
    family: JetbrainsMonoNerdFont
    style: Bold Italic
  size: 12.0

shell:
  program: /bin/bash
EOF
    )
    
    # Create folder
    mkdir -p ~/.config/alacritty
    # Save content to alacritty.yml
    echo "$ALACRITTY_CONTENT" > ~/.config/alacritty/alacritty.yml
    git clone https://github.com/catppuccin/alacritty.git ~/.config/alacritty/catppuccin
    echo -e "${GREEN}Alacritty configuration saved to ~/.config/alacritty.yml${NC}"
else
    echo "Custom setup not implemented in this script. Exiting."
fi

echo -e "${YELLOW}Setting everything up"
echo "============================"
echo

echo "Installing necessary tools: unzip, curl and ripgrep"
echo "---------------------------------------------------------"
if [ "$PM" = "pacman" ]; then
    sudo "$PM" -S --noconfirm unzip curl neovim ripgrep
else
    sudo "$PM" install -y unzip curl ripgrep
fi

echo
echo "Cloning the repository with a secret config name"
echo "-----------------------------------------------"
git clone git@github.com:joaoofreitas/dotnvim.git ~/.config/nvim

echo
echo "Injecting Packer into the system for ultimate package management"
echo "-------------------------------------------------------------"
git clone --depth 1 https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim

echo
echo "Initiating the extraction of Nerd Fonts for maximum awesomeness"
echo "-------------------------------------------------------------"
mkdir -p temp
cd temp
wget https://github.com/joaoofreitas/dotnvim/releases/download/v1.0.0/nerd.zip
unzip nerd.zip

mkdir -p ~/.local/share/fonts
cp *.ttf ~/.local/share/fonts

cd ..
rm -rf temp

echo
echo -e "${GREEN}READY! Get to work by executing 'nvim' and invoking :PackerSync${NC}"
echo -e "${BLUE}==============================================================================================${NC}"

